export const featured = [
  // {
  //   id: 1,
  //   name: "Lavender Sky",
  //   location: "pati-Gangapur, Kollur, Hyderabad ",
  //   projectType: "Apartment",
  //   bedrooms: "2,3 & 4 BHK",
  //   size: "4.07 Acres",
  //   units: "540",
  //   image: "/lavender/2.webp",
  //   route: "/projects/lavender",
  //   brochureLink: "/lavender/borchure.pdf",
  //   badge: "Sales Open",
  // },
  {
    id: 1,
    name: "NRI Green County",
    location: "sadasivpet municipality",
    projectType: "Plotting",
    bedrooms: "-",
    size: "33 Acres",
    units: "463",
    image: "/krushi/g-5.jpg",
    route: "/projects/nri-green",
    brochureLink: "/greenvalley/borchure.pdf",
    badge: "Sales Open",
  },
  {
    id: 2,
    name: "Krushi Gardenia",
    location: "Nagole, Hyderabad",
    projectType: "---",
    bedrooms: "---",
    size: "---",
    units: "---",
    image: "/krushi/banner.jpg",
    route: "/",
    brochureLink: "",
    badge: "Upcoming",
  },
  // {
  //   id: 3,
  //   name: "Krushi Gardenia",
  //   location: "Nagole, Hyderabad",
  //   projectType: "Apartment",
  //   bedrooms: "3,4 BHK",
  //   size: "5.23 Acres",
  //   units: "440",
  //   image: "/krushi/banner.jpg",
  //   route: "/projects/krushi",
  //   brochureLink: "/krushi/borchure.pdf",
  //   badge: "Upcoming",
  // },
];
