export const krushi = {
  bannerImg: "/krushi/banner.png",
  logo: "/krushi/logo.png",
  title: "Krushi Gardenia",
  location:
    " Sy No99/A, 99/E/EE, Ward No 2, Block No.1, Mamatha Nagar Colony,Nagole village, Uppal Mandal, Ranga Reddy Dist, Telangana - 500068",
  type: "Apartment",
  area: "5.23",
  rooms: "3,4 BHK",
  units: 440,
  borchureLink: "/krushi/borchure.pdf",
  about:
    " At Tanmai Constructions, we believe that every project is more than just a structure it&apos;s a reflection of dreams, aspirations, and a vision brought to life. Established with a passion for creating exceptional spaces, we are a new name in the construction.",
  planLink: "/krushi/plan.png",
  amenities: [
    "Coffee shop",
    "Pool side seating desk",
    "Guest rooms",
    "Family swimming pool",
    "Meditation/ yoga hall",
    "Out Door seating decks",
    "Super Market",
    "Uni sex saloon and spa",
    "Clinic",
    "Reception and lounge",
  ],
  gallery: [
    "/krushi/g-1.png",
    "/krushi/g-2.png",
    "/krushi/g-3.png",
    "/krushi/g-4.png",
    "/krushi/g-5.png",
    "/krushi/g-6.png",
    "/krushi/g-7.png",
    "/krushi/g-8.png",
    "/krushi/g-9.png",
    "/krushi/g-10.png",
  ],
};
