export const krushi = {
  bannerImg: "/krushi/banner.jpg",
  logo: "/krushi/logo.png",
  title: "Krushi Gardenia",
  location:
    " Sy No99/A, 99/E/EE, Ward No 2, Block No.1, Mamatha Nagar Colony,Nagole village, Uppal Mandal, Ranga Reddy Dist, Telangana - 500068",
  type: "Apartment",
  area: "5.23",
  rooms: "3,4 BHK",
  units: 440,
  borchureLink: "/krushi/borchure.pdf",
  about:
    " At Tanmai Constructions, we believe that every project is more than just a structure it&apos;s a reflection of dreams, aspirations, and a vision brought to life. Established with a passion for creating exceptional spaces, we are a new name in the construction.",
  planLink: "/krushi/plan.png",
  amenities: [
    "Coffee shop",
    "Pool side seating desk",
    "Guest rooms",
    "Family swimming pool",
    "Meditation/ yoga hall",
    "Out Door seating decks",
    "Super Market",
    "Uni sex saloon and spa",
    "Clinic",
    "Reception and lounge",
  ],
  gallery: [
    "/krushi/g-1.jpg",
    "/krushi/g-2.jpg",
    "/krushi/g-3.jpg",
    "/krushi/g-4.jpg",
    "/krushi/g-5.jpg",
    "/krushi/g-6.jpg",
    "/krushi/g-7.jpg",
    "/krushi/g-8.jpg",
    "/krushi/g-9.jpg",
    "/krushi/g-10.jpg",
  ],
};

export const lavender = {
  bannerImg: "/lavender/2.webp",
  logo: "/lavender/logo.png",
  title: "Lavender Sky",
  location: "pati - Gangapur , Kollur , Hyderabad ",
  type: "Apartment",
  area: "4.07",
  rooms: "2,3 & 4 BHK",
  units: 540,
  borchureLink: "/lavender/borchure.pdf",
  about:
    "Discover 540 well-appointed homes, designed to enhance how you live, work, and play. With resort-style architecture and a touch of luxury, Lavender Skies is an intimate retreat and a smart investment. Located in Prime Pati-Ganapur, Kollur, enjoy West Hyderabad living with easy access to ORR, Kokapet, the Financial District, and RGA International Airport. Surrounded by top schools and leisure spots, Lavender Skies offers a charming and convenient neighborhood. Fine Living. Elevated for You",
  planLink: "/lavender/10.webp",
  amenities: [
    "Reception & Lobby",
    "Saloon/Spa",
    "Conference room",
    "Outdoor seating decks",
    "Coffee shop",
    "Indoor badminton courts",
    "Creche",
    "Kids pool",
    "Cafeteria",
    "Suits",
  ],
  gallery: [
    "/lavender/1.webp",
    "/lavender/2.webp",
    "/lavender/3.webp",
    "/lavender/4.webp",
    "/lavender/5.webp",
    "/lavender/6.webp",
    "/lavender/7.webp",
    "/lavender/8.webp",
    "/lavender/9.webp",
    "/lavender/10.webp",
  ],
};
